### ISSUE TITLE
Possible name change?

### ISSUE THREAD

**Issue by EricEngle-NOAA** [conda-forge/g2clib-feedstock#32]
### Comment:

Posing a general question here.  Is there a process for requesting a name change for a package?

Ideally, the name for this package should be nceplibs-g2c, which would be consistent with nceplibs-sp and nceplibs-ip packages.

Thanks!

**Comment by xylar** [comment]
@EricEngle-NOAA, I'll defer to you and other maintainers about what the right name is for the package.  But I have a PR to change the name as you suggested in #33.  We'll need to keep building a package `g2clib` that just installs the same version of `nceplibs-g2c`, as you can see in that PR.  We could eventually get rid of this if we can be sure all downstream packages are using the new name.

We don't have a good way to rename the `g2clib-feedstock` repo as far as I know.  We would have to create a new one an archive this one if that turns out to be a priority.

**Comment by EricEngle-NOAA** [comment]
I think this works!  I am very new to the conda-forge packing process so I was under the assumption that the name used in this repo has to match the package name used for installation.

**Comment by xylar** [comment]
Yes, the feedstocks certainly do ideally have the same names as the packages, otherwise it's confusing for users trying to find which feedstock makes a given package.  But they can search here if they know to look for it:
https://conda-forge.org/feedstock-outputs/index.html

**Comment by ocefpaf** [comment]
I would not change the name of the feedstock b/c of the bot infrastructure. That would be a bit more complicated and, if you all decide to go that route. I'd rather archive this one and re-submit with the new name.

With that said, @xylar approach if probably the best solution, multiple outputs to ensure folks using the old name and the new one will get the same version moving forward.
